name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject Secrets into JavaScript
        env:
          YOUTUBE_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          echo "Injection des secrets..."
          PASS_HASH=$(echo -n "$ADMIN_PASS" | sha256sum | awk '{print $1}')
          
          # Remplace les placeholders dans les fichiers JS
          sed -i "s|__YOUTUBE_API_KEY__|$YOUTUBE_KEY|g" js/youtube.js
          sed -i "s|__ADMIN_HASH__|$PASS_HASH|g" js/app.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
